SRC = ../src
PROGRAMS := $(patsubst $(SRC)/%.l,%,$(wildcard $(SRC)/*.l)) 
PROGRAMS := $(filter-out main,$(PROGRAMS))

all:
	$(MAKE) -C ..

clean:
	$(MAKE) -C .. clean

$(PROGRAMS): %:
	$(MAKE) -C .. $@
